- name: Deploy container
  hosts: all
  user: root

  tasks:
    - name: Pull image
      docker_image:
        name: ujenjt/miprimer

    - name: Restart a container
      docker_container:
        image: ujenjt/miprimer
        name: miprimer
        state: started
        restart: yes
        pull: yes
        ports:
          - "172.17.0.1:4242:4242"
